(()=>{
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const ball=(color,cls='')=>`<img class="cb-ball ${cls}" src="chalk-assets/cat-${color}.png" alt="${{red:'赤',blue:'青',yellow:'黄',green:'緑'}[color]}の玉">`;
 const btn=(text,action,kind='cream')=>`<button class="cb-btn ${kind}" data-action="${action}">${text}<span aria-hidden="true">›</span></button>`;
 const back=(action='title')=>btn('← もどる',action,'back');
 const panel=content=>`<div class="cb-panel panel">${content}</div>`;
 window.renderApprovedMode=(which,result={},context={})=>{
  let body='',title='',paper=false;result=result||{};
  if(which==='title'){paper=true;body=`<div class="cb-brand"><p>CHALK BLUE</p><h1>スマートボール</h1><div class="cb-ball-row">${['red','blue','yellow','green'].map(c=>ball(c)).join('')}</div><p>引いて、飛ばして、そろえよう。</p></div><button class="cb-mode cb-solo" data-action="solo"><b>ひとりで遊ぶ</b><small>自分のペースでスコアに挑戦！</small>${ball('blue')}</button><button class="cb-mode cb-party" data-action="versus"><b>対戦する</b><small>友だちやCPUと13発勝負！</small>${ball('red')}</button><div class="cb-floor-actions">${btn('ランキング','ranking','tile')}${btn('あそびかた','help','tile')}${btn('設定','settings','tile')}</div>`;}
  if(which==='versus'){title='対戦する';body=`<div class="cb-ball-row">${ball('blue')}${ball('red')}</div>${btn('CPUと対戦','cpu','butter')}${btn('合言葉で対戦','near','party')}${btn('オンライン対戦','match','deep')}<p class="cb-description">1発ずつ交代、ひとり13発。<br>16穴が埋まったら、その時点で終了。</p>${back()}`;}
  if(which==='near'){title='合言葉で対戦';body=panel(`<p>それぞれのスマホで参加しよう！</p>${btn('部屋をつくる','create','butter')}<label for="duel-code">教えてもらった合言葉</label><input id="duel-code" aria-label="合言葉（数字6桁）" placeholder="数字6桁" inputmode="numeric" maxlength="6">${btn('部屋に入る','join','deep')}`)+back('versus');}
  if(which==='lobby'){title='相手を待っています';body=panel('<p>この合言葉を相手に伝えてね。</p><div class="mode-code cb-code"></div>'+btn('合言葉をコピー','copy-code','butter'))+btn('キャンセル','leave','back');}
  if(which==='matching'||which==='reconnect'){title=which==='matching'?'相手を探しています':'接続を確認しています';body=`<div class="cb-ball-row">${ball('blue')}${ball('red')}</div><div class="cb-spinner" role="status" aria-label="待機中"></div><p class="cb-description">${which==='matching'?'対戦相手が見つかるまで待ってね。':'通信が戻るとゲームに戻ります。'}</p>${btn('ホームにもどる','leave','back')}`;}
  if(which==='start'){title='対戦スタート';body=`<div class="cb-ball-row big">${ball('blue')}${ball('red')}</div>`+panel(`<h3><span class="blue">1P 青</span>　VS　<span class="red">2P 赤</span></h3><p>あなたは${(context.seat??0)+1}Pです。${context.seat===1?'後攻':'先攻'}！</p><p>ひとり13発の勝負</p>`);}
  if(which==='pause-menu'||which==='online-menu'){body=panel(`${which==='online-menu'?'<p>対戦中は一時停止しません。</p>':''}${btn('ゲームに戻る','continue','butter')}${which==='pause-menu'?btn('設定','settings'):''}${btn('タイトルへ','leave','back')}`);}
  if(which==='leave'){title='対戦を終了しますか？';body=panel('<p>退出すると、この対戦は終了します。</p>'+btn('対戦に戻る','continue','butter')+btn('退出する','confirm-leave','party'));}
  if(which==='ended'){title='対戦が終了しました';body=panel('<p>相手が退出したか、通信が途切れました。</p>'+btn('もう一度対戦する','match','butter')+btn('ホームにもどる','leave','back'));}
  if(['win','lose','draw'].includes(which)){title='対戦結果';const word={win:'WIN!',lose:'LOSE',draw:'DRAW'}[which];body=`<div class="cb-outcome ${which}"><strong>${word}</strong><p>${{win:'あなたの勝ち！',lose:'次の勝負でリベンジ！',draw:'いい勝負でした！'}[which]}</p><div class="cb-ball-row">${ball('blue')}${ball('red')}</div></div><div class="score-pair cb-scores">${[0,1].map(i=>`<div class="${i?'red':'blue'}"><span>${i+1}P</span><b>${Number(result.scores?.[i]??0).toLocaleString()}</b></div>`).join('')}</div>`+panel(`<div class="row"><b>${result.counts?.[0]??0}個</b><span>入った数</span><b>${result.counts?.[1]??0}個</b></div><div class="row"><b>×${Number(result.multipliers?.[0]??1).toFixed(1)}</b><span>連結倍率</span><b>×${Number(result.multipliers?.[1]??1).toFixed(1)}</b></div>`)+btn('もう一度対戦する','replay','butter')+btn('ホームにもどる','leave','back');}
  if(which==='solo-result'){title='今回のスコア';body=`<div class="cb-ball-row">${ball('blue')}</div>`+panel(`<p>${result.score>=result.best?'自己ベスト更新！':'おつかれさま！'}</p><strong class="total">${Number(result.score??0).toLocaleString()}</strong><p>ベスト ${Number(result.best??0).toLocaleString()}点</p>`)+btn('もう一度遊ぶ','replay','butter')+btn('ランキング','ranking','deep')+back();}
  if(which==='settings'){title='設定';body=panel([['bgm','BGM'],['sound','効果音'],['reduced','演出を控えめに']].map(([key,label])=>{let on=localStorage.getItem('Smartball.'+key)!=='off';return `<div class="row"><b>${label}</b><button class="cb-switch" role="switch" aria-label="${label}" aria-checked="${on}" data-action="toggle-setting" data-setting="${key}"></button></div>`;}).join(''))+btn('保存して戻る','save-settings','butter');}
  if(which==='help'){title='あそびかた';body=panel('<h3>引いて、離して、発射！</h3><p>右下のレバーを下に引いて離すと、玉が飛びます。左右の矢印で穴を回転。</p><h3>同じ色をつなげよう</h3><p>同じ色が4つつながると＋2,000点。5つ以上は倍率もアップ！</p><h3>ひとりモード</h3><p>床に落ちた玉が10個で終了。盤面を埋めると得点を精算して続行。</p><h3>対戦モード</h3><p>青と赤、1発ずつ交代で各13発。16穴が埋まった場合も終了。得点の高い方が勝ち！</p>')+back();}
  if(!body)return null;
  return `<div class="cb-screen ${paper?'cb-paper':''}"><div class="cb-content">${title?`<h2 class="cb-heading">${title}</h2>`:''}${body}<p class="mode-message" role="status"></p></div></div>`;
 };
})();
